//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCRUD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bibliothequeEntities : DbContext
    {
        public bibliothequeEntities()
            : base("name=bibliothequeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresse> Adresses { get; set; }
        public virtual DbSet<Domaine> Domaines { get; set; }
        public virtual DbSet<Emprunter> Emprunters { get; set; }
        public virtual DbSet<Livre> Livres { get; set; }
        public virtual DbSet<Personne> Personnes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
    }
}
